### PR TITLE
Support tapable v2 (fix #9)

### LINKED ISSUE #9: tapable v2 breaks pluginCompatV4
As **tapable v2** create wrapper arround hook classes: that **create TypeError** in function `callHook` of `pluginCompatV4.js`.

```
TypeError: Function has non-object prototype 'null' in instanceof check
    at Function.[Symbol.hasInstance] (<anonymous>)
    at callHook (/home/steven/code/angular-universal/node_modules/webpack-plugin-compat/lib/pluginCompatV4.js:126:13)

```

```js
// lib/pluginCompatV4.js

function callHook(hookClass, obj, name, ...args) {
	const hook = getHook(obj, name);
	if (!hook) {
		throw new Error(`No hook for ${name} in object ${obj.constructor.name}`);
	}
        // vvv EXECUTION OF THE NEXT LINE THROWS A TYPEERROR vvv
	if (!(hook instanceof hookClass)) {
		throw new Error(`Attempt to call ${hook.constructor.name} from a ${hookClass.name} call`);
	}
	const method = hookClass.name.startsWith("Async") ? "callAsync" : "call";
	return hook[method](...args);
}
```

Example of tapable hook class between tapable v1.1.3 and tapable v2.0.0: 

```js
// https://github.com/webpack/tapable/blob/v1.1.3/lib/SyncHook.js
// ...
class SyncHook extends Hook {
  // ...
}

module.exports = SyncHook;

// https://github.com/webpack/tapable/blob/v2.0.0/lib/SyncHook.js
// ...
function SyncHook(args = [], name = undefined) {
	const hook = new Hook(args, name);
	hook.constructor = SyncHook;
	// ...
	return hook;
}

SyncHook.prototype = null;

module.exports = SyncHook;
```

**We can see that the hook class prototype is set with `null`: that explain the TypeError.**

@chuckdumont 
_How do you think about this workaround?_

```diff
-	if (!(hook instanceof hookClass)) {
+	if (!(hookClass.prototype ? hook instanceof hookClass : hook.constructor.name === hookClass.name)) {
```

### PR DESCRIPTION
**Pull request by enten**
MR to fix #9

### CODE REVIEW

**Comment by chuckdumont** [comment]
This looks reasonable, but is it the only change needed to support tapable_v2?  I'd like to see the unit tests run using v2.  Update travis.yml to add another env for v2 and make sure the tests pass.

**Comment by enten** [comment]
@chuckdumont 

> This looks reasonable, but is it the only change needed to support tapable_v2?

It's needed to support webpack v5 because [it uses tapable v2.x.x](https://github.com/webpack/webpack/blob/master/package.json#L28).

> I'd like to see the unit tests run using v2. Update travis.yml to add another env for v2 and make sure the tests pass.

I will try to do that.

**Comment by enten** [comment]
@chuckdumont 
Finally, when I'm updating tests for tapable v2 I updated the main change in webpackCompatV4.js as:

```diff
-	if (!(hook instanceof hookClass)) {
+	if (hook.constructor.name !== hookClass.name) {
```

As reminder the previous change suggestion was:

```diff
-	if (!(hook instanceof hookClass)) {
+	if (!(hookClass.prototype ? hook instanceof hookClass : hook.constructor.name === hookClass.name)) {
```

In fact, the previous change suggestion is impossible to test with the current testing setup:

* with tapable v1 (webpack v4), `hookClass.prototype` will always be `true` ;
* with tapable v2 (webpack v5), `hookClass.prototype` will always be `null` ;
* and overriding of a function `prototype` is impossible.

I think that testing the previous change suggestion needs too many changes and doesn't really make sense.

That's why I updated the main change suggestion.

**Comment by chuckdumont** [comment]
@enten -thanks for doing this!

**Comment by chuckdumont** [comment]
@enten - I'm not comfortable with changing the pre-2.0 behavior, so I modified you're changes to keep old behavior with using instanceof for tapable 1.x.  See #12

**Pull request merged**
